In [1]:
from denoising_diffusion_pytorch.my_classifier_free import *

/Users/chocho/Library/r-miniconda-arm64/lib/python3.10/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/Users/chocho/Library/r-miniconda-arm64/lib/python3.10/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')


In [2]:
ds = MyDataset(
      '/Users/chocho/Downloads/celebA/img_align_celeba',
      image_size=64,
      list_attr_celeba_path = '/Users/chocho/Downloads/celebA/list_attr_celeba.csv',
      condition_attr = ['Male','Smiling'],
    )

In [25]:
ds.images_we_have

['000003.jpg',
 '000007.jpg',
 '000016.jpg',
 '000018.jpg',
 '000020.jpg',
 '000027.jpg',
 '000030.jpg',
 '000034.jpg',
 '000037.jpg']

In [27]:
dl = DataLoader(ds,batch_size=len(ds))

In [33]:
torch.concat(tuple(list(dl)[0]),dim=0)

TypeError: expected Tensor as element 2 in argument 0, but got tuple

In [26]:
ds_list = []
for i in ds:
  print(i[0].view(-1).unsqueeze(0).shape)
  ds_list.append(i[0].view(-1).unsqueeze(0))

torch.Size([1, 12288])
torch.Size([1, 12288])
torch.Size([1, 12288])
torch.Size([1, 12288])
torch.Size([1, 12288])
torch.Size([1, 12288])
torch.Size([1, 12288])
torch.Size([1, 12288])
torch.Size([1, 12288])


In [39]:
torch.concat(ds_list).shape

torch.Size([9, 12288])

In [22]:
label_list = []
for i in ds:
  label_list.append(i[1])

In [24]:
label_list

[2, 2, 3, 1, 2, 1, 2, 0, 2]

In [6]:
ds.num_classes

4

In [6]:
ds.df_attr

image_id  condition_attr
2   000003.jpg               2
6   000007.jpg               2
15  000016.jpg               3
17  000018.jpg               1
19  000020.jpg               2
26  000027.jpg               1
29  000030.jpg               2
33  000034.jpg               0
36  000037.jpg               2

In [18]:
torch.arange(18).reshape(2,3,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [17]:
torch.arange(18).reshape(2,3,3).view(2,-1)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [19]:
for i in ds:
  print(i[0].view(-1))
  break

tensor([-0.8118, -0.5922, -0.2627,  ..., -1.0000, -1.0000, -1.0000])


In [54]:
train_data1.shape

torch.Size([60000, 784])

In [55]:
import numpy as np
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
from datasets import load_dataset
import torch
from torchvision import transforms
pil_to_tensor = transforms.ToTensor()
# tensor_to_pil = transforms.ToPILImage()
def tensor_to_pil(x:torch):
    return transforms.ToPILImage()(x.clamp(0,1))

# Load MNIST dataset
dataset = load_dataset("mnist")
train_data = [pil_to_tensor(img).flatten().unsqueeze(0) for img in dataset['train']['image']]
train_data1 = torch.concat((train_data),dim=0)

# Perform t-SNE on the dataset
tsne = TSNE(n_components=2, random_state=42)
tsne_result = tsne.fit_transform(train_data1)

# Create a scatter plot of the t-SNE embeddings
plt.figure(figsize=(10, 8))
plt.scatter(tsne_result[:, 0], tsne_result[:, 1], c=dataset['train']['label'], cmap='viridis', alpha=0.5)
plt.title('t-SNE Visualization of MNIST')
plt.colorbar()
plt.show()

KeyboardInterrupt: 